application:
    plaintsis:
            username: UsuGepep
            password: ZZZCONFZZZGEPEPBRZZZBUSINTZZZUSUGEPEPZZZINTZZZ
            sincrosauce:
                registros: 500
                ofuscar: true
                permiteAnio: true
            ldap: ldaps://ldapeducainteg.princast.org
            instructionSchedularTime: 0 5 0 10 1 ?
            services:
              sauce:
                endpoint: https://integosb.princast.org/SistemasVerticales/wsSauce/2.0
    cors:
      allowed-origins:
        - "*"
      allowedMethods:
        - "*"
      allowedHeaders:
        - "*"
    conveniob:
      fechaconveniob: 2022-06-01T00:00:00
management:
  endpoints:
    web:
      exposure:
        include: health
