version: '2.3'

services:

  keycloak:
      image: quay.io/keycloak/keycloak:15.0.2
      container_name: keycloak
      environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=pikathnoOoEezsSc0l8ZCfZs
      ports:
        - "18443:8443"
      extra_hosts:
        - ldapeducainteg.princast.org:10.154.48.11        
      volumes:
        - ${DOCKER_PATH}/keycloak/data:/opt/jboss/keycloak/standalone/data/
        - ${DOCKER_PATH}/keycloak/config:/opt/jboss/config/