logging.level.org.springframework.security: DEBUG
application:
  gitlab:
    url: http://gitlab/api/v4
    token: glpat-wQ3iHZuGBwAKvg_C6s4m
    defaultPassword: Mandaloriano100
  roles:
    - id: 50
      name: owner
    - id: 40
      name: maintainer
    - id: 30
      name: developer
    - id: 20
      name: reporter
    - id: 10
      name: guest
  cors:
    allowed-origins:
      - '*'
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders:
      - '*'      