spring:
    messages:
        basename: /WEB-INF/classes/messages
    reports:
        basename: /WEB-INF/classes/reports
    config:
        basename: /WEB-INF/classes/config    
    datasource:
        jndi-name: java:/jdbc/gepepDS

    servlet:
        multipart:
          location: ${config.path:/opt/jboss/WEBAPPS}/services/gepep/file_storage
          enabled: true
          file-size-threshold: 2MB
          max-file-size: 20MB
          max-request-size: 20MB

application:
    external.resources.location: "file:${config.path:/opt/jboss/WEBAPPS}/services/gepep/config/*.yml"

logging:
    config: "file:${config.path:/opt/jboss/WEBAPPS}/services/gepep/config/logback-spring.xml"
